fix(debian): improve preinst and prerm behavior
pop-os/repolib pull request #43
Opened 2022-05-02 17:11 UTC by isantop

Rewrite the preinst script (and add a prerm script) that will
improve fault tolerance for certain situations that may be
encountered depending on packages and user-setup on systems. This
ensures that we only create a symlink for add-apt-repository if
it isn't already present, that we don't attempt to create a
duplicate (and fail) if we're already managing it, and we don't
remove them unless we are the ones who set it up.

This also splits handling of both add-apt-repository and
apt-add-repository into separate sections so that we can handle
them individually.

2022-05-02 17:28 UTC, mmstick approved these changes

2022-05-02 21:11 UTC, n3m0-22 submitted a review, later dismissed
I was able to replicate the issue, and can confirm this fixes it. It also passed all testing.
[repolib_tests.txt](https://github.com/pop-os/repolib/files/8606052/repolib_tests.txt)

2022-05-02 22:02 UTC, jacobgkau commented
If I had `software-properties-common` installed on a system and then I remove it, then I can no longer run that command, even though I still have `python3-repolib` installed. Is that what we want?

2022-05-02 22:10 UTC, jacobgkau requested changes
Actually, I'm not seeing this create the link even if I reinstall/reconfigure it (or just run the script manually) without having `software-properties-common` installed.

Looking at the bash script, wouldn't the lines to create the link need to go _outside_ of the if statement checking whether the link target already exists?

2022-05-03 18:01 UTC, isantop commented
@jacobgkau 

> If I had software-properties-common installed on a system and then I remove it, then I can no longer run that command, even though I still have python3-repolib installed (because the preinst script is only run when python3-repolib is being configured.) Is that what we want?

I don't think there's a better way to do it without severely breaking debian guidelines. 

> Looking at the bash script, wouldn't the lines to create the link need to go outside of the if statement checking whether the link target already exists?

Yep! That was a mistake, should now be fixed in 49fc5f8

2022-05-03 18:13 UTC, isantop commented
I might be able to use a dpkg trigger to let repolib take over `add-apt-repository` if software-properties is removed. I don't think we should consider that blocking for this PR, as the current state is causing failed upgrades and we should fix that as soon as possible.

2022-05-03 20:24 UTC, jacobgkau commented
> I don't think there's a better way to do it without severely breaking debian guidelines.

I'm confused why doing this in a postinst script at all is more in line with Debian guidelines than providing the link we intend to provide and conflicting with the other package that would provide that link. If this was important enough to need two different versions of `add-apt-repository` floating around (which it doesn't seem like it is), then the update-alternatives system would be the "Debian way" of doing it, right? Not detecting this ourselves in a script.

2022-05-03 20:32 UTC, jacobgkau approved these changes
As it stands right now, the script works to place the link at `/usr/bin/add-apt-repository` when `software-properties-common` is not installed. If I install `software-properties-common`, it just overwrites our link with their version (which isn't a link, just a directly-installed file.) After that, reinstalling `python3-repolib` skips adding the link. Removing `software-properties-common` at this point leaves me without an `add-apt-repository` command.

I'm approving this since it fixes the flawed assumption made in the current version that the file would only exist if `software-properties-common` was installed, but this still seems like a massive hack.

2022-05-03 23:05 UTC, merged