Bugfixes
pop-os/repolib pull request #54
Opened 2022-10-11 17:37 UTC by isantop

Fixes #51 
When adding a `popdev:` shortcut, slashes are an invalid character for staging branches, so they should never be allowed in `popdev:` shortcuts. Additionally, if the user enters `popdev/` instead of `popdev:`, print the suggested correction to console with the error. Also adds a suggestion for missing branches where the user entered the branch using the `add` format `popdev:branchname` instead of the `remove` format `popdev-branchname` if such a branch exists, and offers to use that instead without modifying the command entered (Feedback from QA).

Fixes #52 
When adding a `popdev:` shortcut with a branch name containing dots, the preferences file written contains those dots, leading Apt to ignore the preferences file (and subsequently not update those packages). This ensures that the preferences files written by Repolib do not contain dots, while ensuring that the dots are preserved in the `.sources` entry as well as the preferences file (as they are required for the URI).

Fixes #53
Corrects a typo in the `remove` subcommand as demonstrated in #53

2022-10-11 17:40 UTC, 13r0ck approved these changes

2022-10-12 19:28 UTC, n3m0-22 requested changes
All the fixes are working as expected from what I can tell. The suggested command fixes for malformed `add` and `remove` are a nice addition. This is very useful when replacing `add` with `remove` from a previous command and forgetting to replace the `:` with a `-`. Branches with dots in the name are being added and functioning correctly. The `remzove`/`remove` typo is corrected.

A potential issue I'm seeing is a branch can be added with a typo e.g., `popdev;51-52-53-fixes` instead of `popdev:51-52-53-fixes`. This results in an empty source being added. I think accidentally using a semicolon vs the colon is the most likely mistake, but it seems any character can be used as a delimiter not including `/`, which correctly gives the suggestion to replace with `:`, and not return an error. When using `remove` with the exception of `:` and `-` other characters generate an error. Perhaps a similar functionality can be added to `add` by only allowing for a `:`.

2022-10-12 21:35 UTC, isantop commented
@n3m0-22 Good catch! I added some additional checking to spit out more meaningful errors and offer more helpful suggestions for more cases. I can't do much for the case of semicolons, as the shell interprets that as a command delimiter so that will always fail with the following message:

```
$ apt-manage add popdev;master
Fetching repository information...
apt-manage: ERROR: The shortcut "popdev" is malformed
```

because `master` in this case is being treated as a separate command by the shell; a branch name which legitimately requires the semicolons would need to be wrapped in `""` first, so the typo potential is low. Nonetheless, even including that and wrapping it in quotes produces the correct error:

```
$apt-manage add "popdev;master"
Fetching repository information...
apt-manage: ERROR: The shortcut "popdev;master" is malformed
Did you mean "popdev:master"?
```

As a bonus, this also works for `ppa:` shortcuts (although there is probably more suggestion potential there, I think that would be best handled by a separate PR)

This is all present as of d35494a

2022-10-12 22:36 UTC, n3m0-22 commented
The initial issue is fixed, but I'm seeing something from the suggestions when using `add`. 

Add a branch with dashes in the name. 

`apt-manage add popdev-51-52-53-fixes` 

It will recommend replacing all the dashes with colons not just the first one. 

```
Fetching repository information...
apt-manage: ERROR: The shortcut "popdev-51-52-53-fixes" is malformed
Did you mean "popdev:51:52:53:fixes"?

```

This will be a problem for any branch with dashes in the name.

2022-10-13 17:22 UTC, isantop commented
@n3m0-22 That was an easy fix, should be good as of b9543ed

2022-10-13 18:07 UTC, n3m0-22 approved these changes
Looks good. All the issues mentioned have been resolved.

2022-10-13 18:12 UTC, merged